# run build.sh, upload ~/build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./build.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ~/build
