# run build.sh, upload ~/build
name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ARCH: [x86_64, aarch64, arm]
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
        env:
          ARCH: ${{ matrix.ARCH }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.ARCH }}
          path: ~/android/build
